// =============================================================================
// Zone 3 — "The Open Sea"  ·  a sailing surface over a dive-heavy seafloor
// -----------------------------------------------------------------------------
// Two playfields stacked on ONE heightfield:
//   SURFACE  — sparse open blue water, one island + one pinnacle islet. Sailing.
//   SEAFLOOR — the content: a trench, a deep basin, canyon systems, terraced
//              plateaus, calm sandy floors. Diving.
//
// The heightfield comes from a hand-painted band map (map.png) through
// core/terrain-from-map.js — same pipeline lagoon uses, with that loader's new
// oblong extentX/extentZ support (this zone is 600 x 300 world units from a
// 2000 x 1000 map, 3.33 px per world unit on both axes).
//
// Coordinate convention: X east, Z south, Y up. Sea level is WATER_Y.
// "depth" everywhere means (WATER_Y - terrainHeight): positive = underwater.
// The painted map itself is generated by ./paint-map.js — that file is the
// editable source of the topology (shape fields), map.png is its output.
// =============================================================================
import { loadTerrainMap } from '../../core/terrain-from-map.js';

// ─────────────────────────────────────────────────────────────────────────────
//  WORLD CONSTANTS
// ─────────────────────────────────────────────────────────────────────────────
export const WORLD_EXTENT_X = 300;  // world spans [-300, 300] on X (east-west, the long axis)
export const WORLD_EXTENT_Z = 150;  // world spans [-150, 150] on Z (north-south)
export const WORLD_EXTENT   = WORLD_EXTENT_X; // zone-contract scalar (shell reads this for cull/limits)
export const WATER_Y = 0;

// ─────────────────────────────────────────────────────────────────────────────
//  BAND -> HEIGHT LEGEND
//  Same discipline as lagoon: the three shallow bands are derived from
//  character/controller.js's footing thresholds (WADE_START=0.45,
//  SWIM_DEPTH=1.2, STEP_UP=0.5); the five dive bands are a DEPTH LADDER, each
//  roughly double the previous, so a descent reads as distinct "floors".
//    LAND     +3.4   dry island crown (well above STEP_UP)
//    SAND     -0.25  runnable wet shallows      (mid 0 .. WADE_START)
//    WADE     -0.85  walk-only                  (mid WADE_START .. SWIM_DEPTH)
//    SHOAL    -3.0   snorkel depth, ridge crests / seamount top — floor bright
//    PLATEAU  -8.0   comfortable dive depth, floor clearly visible
//    FLOOR    -16.0  open sandy floor (lagoon's old DEEP_FLOOR_Y precedent)
//    SLOPE    -30.0  the deep slope the features sit in — floor barely read
//    TRENCH   -52.0  trench + basin bottom; near-dark, biolum territory
//  Total Y-range 55.4 units: a full-depth dive from island beach to trench
//  floor, which is what makes the underwater the star.
// ─────────────────────────────────────────────────────────────────────────────
const LEGEND = [
  { id: 'LAND',    color: '#ff8000', height:  3.4 },
  { id: 'SAND',    color: '#ffe600', height: -0.25 },
  { id: 'WADE',    color: '#7cff2e', height: -0.85 },
  { id: 'SHOAL',   color: '#00e5ff', height: -3.0 },
  { id: 'PLATEAU', color: '#0f9dff', height: -8.0 },
  { id: 'FLOOR',   color: '#0b57d0', height: -16.0 },
  { id: 'SLOPE',   color: '#16277f', height: -30.0 },
  { id: 'TRENCH',  color: '#08103a', height: -52.0 },
];
export const BAND_LEGEND = LEGEND;

// blurRadius 4 / 2 passes at 3.33 px per unit  ->  ~3 world units of transition.
// Deliberately TIGHTER than lagoon's (4/3): on a 22-unit band step (SLOPE ->
// TRENCH) that reads as a proper canyon wall you swim along, not a ramp, while
// still giving the island a walkable beach (its band steps are under a unit).
export const { terrainHeight, bandAt } = await loadTerrainMap(
  new URL('./map.png', import.meta.url).href,
  LEGEND,
  {
    extentX: WORLD_EXTENT_X,
    extentZ: WORLD_EXTENT_Z,
    tolerance: 0,
    blurRadius: 4,
    blurPasses: 2,
    // Detail noise per band: flat where footing matters, coarse and big-
    // amplitude in the deeps so the trench floor and slope read as rough
    // ground rather than a painted plane.
    noiseAmp:   { LAND: 0.5, SAND: 0, WADE: 0, SHOAL: 0.35, PLATEAU: 0.7, FLOOR: 1.2, SLOPE: 2.2, TRENCH: 3.0 },
    noiseScale: { LAND: 0.09, SHOAL: 0.06, PLATEAU: 0.05, FLOOR: 0.03, SLOPE: 0.018, TRENCH: 0.012 },
  }
);

export function depthAt(x, z) { return WATER_Y - terrainHeight(x, z); }

export function terrainNormal(x, z, eps = 0.5) {
  const hL = terrainHeight(x - eps, z);
  const hR = terrainHeight(x + eps, z);
  const hD = terrainHeight(x, z - eps);
  const hU = terrainHeight(x, z + eps);
  const nx = hL - hR;
  const nz = hD - hU;
  const ny = 2 * eps;
  const len = Math.hypot(nx, ny, nz) || 1;
  return [nx / len, ny / len, nz / len];
}

// ─────────────────────────────────────────────────────────────────────────────
//  LANDMARKS — the painted features, as data. Not fed into terrainHeight (the
//  map is), but the fx layer reads them (vent plumes in the trench, fish
//  schools over the plateaus, current lanes down the canyons) and gameplay
//  will want them for navigation / spawn logic later.
// ─────────────────────────────────────────────────────────────────────────────
export const LANDMARKS = {
  islands: [
    { name: 'Gullhook',    x: -214, z: -104, r: 27, peak: 4.2 }, // the one real island: beach, palms, resupply
    { name: 'Spire Tooth', x:   26, z:   92, r:  7, peak: 2.6 }, // the seamount's tip, breaks the surface
  ],
  // "The Sunder" — the main trench, west-to-east across the whole zone.
  trench: [[-300, -58], [-212, -28], [-150, 10], [-70, 40], [12, 54], [96, 26], [162, 46], [236, 74], [300, 60]],
  trenchBranch: [[104, 32], [126, 72], [132, 112], [118, 148]],
  basin: { x: -12, z: 44, rx: 92, rz: 52, floor: -40 },   // deep central basin, merges with the trench
  plateaus: [
    { name: 'Pale Tables',  x: -196, z: -86, rx: 106, rz: 60 },
    { name: 'Sunstep Shelf', x: 172, z: -74, rx: 122, rz: 66 }, // terraced: ridge crests + canyon fingers
    { name: 'Combs',         x: 210, z:  92, rx:  78, rz: 44 },
    { name: 'Lowmeadow',     x: -100, z: 112, rx: 62, rz: 34 },
  ],
  // Canyon axes (narrow deep channels between ridges) — fx uses these as
  // current lanes; the map is where their shape actually lives.
  canyons: [
    [[-206, -118], [-192, -78], [-176, -38], [-156, 2]],
    [[-124, -136], [-114, -90], [-106, -44], [-98, 6]],
    [[ 126, -130], [ 142, -86], [ 148, -40], [ 152, 12]],
    [[ 198, -120], [ 208, -74], [ 216, -24], [ 224, 26]],
    [[  44,  -98], [  12, -66], [ -16, -32], [ -30, 10]],
    [[ 246,  -96], [ 262, -52], [ 268,  -8]],
    [[ 196,   62], [ 190,  96], [ 186, 134]],
    [[ 232,   70], [ 246, 104], [ 258, 138]],
    [[ 156,   84], [ 132, 112], [ 108, 140]],
  ],
  seamount: { name: 'The Spire', x: 26, z: 92, baseR: 62, top: 2.6 }, // -30 floor to above water in ~60 units
  // Sandy calm floors — the "quiet" beats between intricate stretches.
  openFloors: [
    { x: -220, z:  96, rx: 132, rz: 54 },
    { x:  256, z: -16, rx:  92, rz: 82 },
    { x:  -34, z: -118, rx: 124, rz: 42 },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
//  PLACED GEOMETRY — the ONLY things that are not painted terrain. The
//  heightfield physically cannot overhang (one Y per XZ), so every roof-over-
//  your-head moment is a prop sitting ON the heightfield, flagged here.
//  Kept to three, all at deliberate dive destinations.
// ─────────────────────────────────────────────────────────────────────────────
export const PLACED_GEOMETRY = [
  { id: 'sunder-gate',  kind: 'arch',   x: -70, z:  40, note: 'drowned arch straddling the trench axis — the "gate" you descend through' },
  { id: 'spire-tunnel', kind: 'tunnel', x:  40, z:  78, rotY: -0.7, note: 'short swim-through tunnel at the seamount base' },
  { id: 'comb-arch',    kind: 'arch',   x: 190, z:  96, note: 'arch spanning a canyon mouth on the Combs' },
];

// ─────────────────────────────────────────────────────────────────────────────
//  PALETTES — same shape as lagoon's (so the fx controller is a drop-in), but
//  graded for OPEN OCEAN: colder, deeper, less turquoise; the underwater block
//  gains `abyss*` + `deepBiolum` fields the open-sea fx reads for its
//  depth-darkening and deep-plankton systems.
// ─────────────────────────────────────────────────────────────────────────────
export const PALETTES = {
  // ── DAY: high sun, hard horizon, cobalt water. Sailing weather. ────────────
  day: {
    sky: '#8fc7e8',
    fog:        { color: '#bcdcec', near: 90, far: 420 },   // far: the stage has to feel big
    hemisphere: { sky: '#d8ecf8', ground: '#5b86a8', intensity: 0.9 },
    sun:        { color: '#fff6e2', intensity: 1.6, direction: [0.36, 0.84, 0.24] },
    water: {
      opacity: 0.965,                                        // open sea is NOT see-through
      depthStops: [[0.0, '#6fd0d8'], [4.0, '#1585b8'], [16.0, '#0b3f7e'], [40.0, '#06183f']],
      surfaceTint: '#bde2f2', sunColor: '#fff6df', shimmer: 0.75,
      foam: '#f2f9ff', foamBand: 0.5,                        // shore foam is minor here...
      whitecap: 0.55,                                        // ...crest whitecaps carry the surface instead
      swellAmp: 0.62, swellScale: 0.055,                     // long rolling swell (lagoon: 0.12 / 0.16)
      ceiling: '#a8dcec', sunDisc: '#fff2cc',
    },
    terrain: { sand: '#e2cfa4', wetSand: '#c4ab80', rock: '#8e9a9c', deepTint: '#27505f' },
    terrainGrade: '#ffffff',
    bloom: { strength: 0.5, radius: 0.55, threshold: 0.84 },
    underwater: {
      // Open-ocean water is CLEAR: far ~90 units, so canyon walls, ridges and
      // the far trench rim all stay legible. (Lagoon runs 0.030 = ~33 units,
      // which would erase this zone's topology.)
      fogColor: '#0a5f86', fogDensity: 0.011,
      tint: '#1591b4', tintStrength: 0.16,
      ambient: 0.55,
      causticStrength: 1.0, causticMaxDepth: 16.0,           // caustics die off past the plateaus
      godrayColor: '#e8fbff', godrayStrength: 0.75, godrayMaxDepth: 30.0,
      moteColor: '#dceff6',
      bioluminescence: 0.0,
      abyssColor: '#03102c', abyssStart: 26.0, abyssFull: 56.0, // depth-darkening ramp: the trench, not the plateaus
      deepBiolum: 0.5,                                        // plankton below abyssStart glow even by day
      currentStrength: 0.55,                                  // drift-streak fx
    },
  },

  // ── AFTERNOON: brightest, warmest, longest sightlines. ────────────────────
  afternoon: {
    sky: '#a9d6ea',
    fog:        { color: '#cfe6ec', near: 100, far: 440 },
    hemisphere: { sky: '#e4f2f6', ground: '#6f93a8', intensity: 1.0 },
    sun:        { color: '#ffe9bc', intensity: 1.85, direction: [-0.08, 0.7, -0.38] },
    water: {
      opacity: 0.965,
      depthStops: [[0.0, '#7edcda'], [4.0, '#1b95bc'], [16.0, '#0d4784'], [40.0, '#071b42']],
      surfaceTint: '#d6ecf0', sunColor: '#fff2cf', shimmer: 0.85,
      foam: '#f6fbff', foamBand: 0.5, whitecap: 0.62,
      swellAmp: 0.7, swellScale: 0.05,
      ceiling: '#b6e4ea', sunDisc: '#ffe9b0',
    },
    terrain: { sand: '#e2cfa4', wetSand: '#c4ab80', rock: '#8e9a9c', deepTint: '#27505f' },
    terrainGrade: '#fff4e6',
    bloom: { strength: 0.55, radius: 0.55, threshold: 0.82 },
    underwater: {
      fogColor: '#0c688e', fogDensity: 0.0095,
      tint: '#1c9ab8', tintStrength: 0.15,
      ambient: 0.58,
      causticStrength: 1.1, causticMaxDepth: 17.0,
      godrayColor: '#fff6e6', godrayStrength: 0.9, godrayMaxDepth: 32.0,
      moteColor: '#eaf6f2',
      bioluminescence: 0.0,
      abyssColor: '#04122e', abyssStart: 28.0, abyssFull: 58.0,
      deepBiolum: 0.45,
      currentStrength: 0.5,
    },
  },

  // ── DUSK: low gold sun on a purple sea; the deep goes violet-black. ───────
  dusk: {
    sky: '#d9a7b8',
    fog:        { color: '#e0b6b8', near: 70, far: 360 },
    hemisphere: { sky: '#eec2cf', ground: '#7a6e94', intensity: 0.8 },
    sun:        { color: '#ffab6e', intensity: 1.0, direction: [-0.56, 0.26, -0.46] },
    water: {
      opacity: 0.96,
      depthStops: [[0.0, '#e9b6b6'], [4.0, '#8f7fc0'], [16.0, '#3f3e84'], [40.0, '#14113a']],
      surfaceTint: '#ffd2d8', sunColor: '#ffd7a2', shimmer: 0.9,
      foam: '#fbe8de', foamBand: 0.5, whitecap: 0.5,
      swellAmp: 0.78, swellScale: 0.05,
      ceiling: '#c9a6c4', sunDisc: '#ffcd94',
    },
    terrain: { sand: '#e2cfa4', wetSand: '#c4ab80', rock: '#8e9a9c', deepTint: '#27505f' },
    terrainGrade: '#ffcfd4',
    bloom: { strength: 0.85, radius: 0.6, threshold: 0.62 },
    underwater: {
      fogColor: '#4d4590', fogDensity: 0.015,
      tint: '#7d68b4', tintStrength: 0.2,
      ambient: 0.48,
      causticStrength: 0.7, causticMaxDepth: 11.0,
      godrayColor: '#ffcdb4', godrayStrength: 0.6, godrayMaxDepth: 20.0,
      moteColor: '#efd6ff',
      bioluminescence: 0.55,
      abyssColor: '#080826', abyssStart: 22.0, abyssFull: 52.0,
      deepBiolum: 0.8,
      currentStrength: 0.6,
    },
  },

  // ── NIGHT: moonlit swell, black water, the trench full of plankton. ───────
  night: {
    sky: '#0b1030',
    fog:        { color: '#101c46', near: 50, far: 320 },
    hemisphere: { sky: '#2c3c78', ground: '#1d2444', intensity: 0.45 },
    sun:        { color: '#a8b8ff', intensity: 0.65, direction: [-0.28, 0.68, -0.3] },
    water: {
      opacity: 0.975,
      depthStops: [[0.0, '#3c4f8e'], [4.0, '#243a84'], [16.0, '#111f56'], [40.0, '#050a20']],
      surfaceTint: '#4b5c9e', sunColor: '#ccd6ff', shimmer: 0.95,
      foam: '#96a8d4', foamBand: 0.5, whitecap: 0.7,          // moonlit crests are the main read at night
      swellAmp: 0.86, swellScale: 0.048,
      ceiling: '#141f4c', sunDisc: '#e4ecff',
    },
    terrain: { sand: '#54503f', wetSand: '#413e30', rock: '#4a4844', deepTint: '#1c333c' },
    terrainGrade: '#6e78bc',
    bloom: { strength: 1.2, radius: 0.62, threshold: 0.48 },
    underwater: {
      fogColor: '#08183e', fogDensity: 0.024,
      tint: '#0f1f52', tintStrength: 0.28,
      ambient: 0.34,
      causticStrength: 0.35, causticMaxDepth: 9.0,
      godrayColor: '#b4c8ff', godrayStrength: 0.35, godrayMaxDepth: 16.0,
      moteColor: '#9fd0ff',
      bioluminescence: 1.0,
      abyssColor: '#01040f', abyssStart: 16.0, abyssFull: 46.0,
      deepBiolum: 1.0,
      currentStrength: 0.65,
    },
  },
};

export const dayCycle = [
  { t: 0.0,  key: 'day' },
  { t: 0.35, key: 'afternoon' },
  { t: 0.65, key: 'dusk' },
  { t: 1.0,  key: 'night' },
];

// ─────────────────────────────────────────────────────────────────────────────
//  SCATTER RECIPE — deliberately THIN (brief: terrain is the content). Four
//  kinds, all reading as "this depth band is alive", none dense enough to
//  hide topology. Depths are chosen off the band ladder above.
// ─────────────────────────────────────────────────────────────────────────────
export const scatterRecipe = {
  seed: 60451,
  area: { minX: -295, maxX: 295, minZ: -145, maxZ: 145 },
  kinds: [
    // ── MEADOWS ──────────────────────────────────────────────────────────────
    {
      id: 'seagrass',    // shallow meadows: the ground cover the shoals were missing
      count: 2600, minDepth: 0.6, maxDepth: 7.0, slopeMin: 0.8, place: 'seabed',
      clump: 9, clumpCount: 30,
      height: [0.35, 1.0], sway: 1.25, swayScale: 1.15,
      colors: ['#5f9350', '#4d8a5e', '#71a04f', '#3f7b58'],
      colorNight: '#16331f', colorsNight: ['#1b3a24', '#153427', '#20402a'], glowNight: 0.05,
    },
    {
      id: 'kelp',        // stands on the plateaus — vertical scale cue for depth
      count: 1100, minDepth: 4.0, maxDepth: 21.0, slopeMin: 0.5, place: 'seabed',
      clump: 13, clumpCount: 26,
      height: [2.6, 9.0], sway: 0.95, swayScale: 0.65,
      colors: ['#3d7a55', '#4a7a3c', '#31684f'],
      colorNight: '#12302c', colorsNight: ['#12302c', '#14301f'], glowNight: 0.1,
    },
    // ── REEF ─────────────────────────────────────────────────────────────────
    {
      id: 'seafan',      // tall flat fans on ridge crests + canyon rims: reads the topology, doesn't hide it
      count: 520, minDepth: 2.0, maxDepth: 13.0, slopeMin: 0.3, place: 'seabed',
      clump: 11, clumpCount: 14,
      scale: [0.8, 2.4], sway: 0.35, swayScale: 0.5,
      colors: ['#c8567e', '#8a5bb4', '#d98a52'],
      colorNight: '#e0699a',
      colorsNight: ['#e0699a', '#a273d6', '#f0a566'], glowNight: 0.7,
    },
    {
      id: 'brain',       // coral heads on the shoals — solid, rounded mass against all the blades
      count: 520, minDepth: 1.4, maxDepth: 11.0, slopeMin: 0.7, place: 'seabed',
      clump: 8, clumpCount: 10,
      scale: [0.35, 1.3], sway: 0, roughness: 0.94, solid: true, sink: 0.14,
      colors: ['#c98a5e', '#b8686e', '#d8a76a', '#9d7fb0'],
      colorNight: '#4a3242', colorsNight: ['#59394a', '#4a3242'], glowNight: 0.15,
    },
    {
      id: 'branch',      // staghorn thickets at the reef edge
      count: 460, minDepth: 2.0, maxDepth: 12.5, slopeMin: 0.6, place: 'seabed',
      clump: 7, clumpCount: 12,
      scale: [0.6, 1.9], sway: 0.12, swayScale: 0.35, roughness: 0.9, solid: true,
      colors: ['#e0906f', '#d76a8e', '#c07fd0', '#e8b07a'],
      colorNight: '#6a3c58', colorsNight: ['#7a4560', '#63406e'], glowNight: 0.35,
    },
    {
      id: 'anemone',     // soft accents, and the daytime hint of the biolum to come
      count: 420, minDepth: 2.5, maxDepth: 24.0, slopeMin: 0.62, place: 'seabed',
      clump: 6, clumpCount: 7,
      scale: [0.3, 0.85], sway: 0.5, swayScale: 0.9,
      colors: ['#e2637f', '#d9a24e', '#7fb8d6'],
      colorNight: '#ff7fa8', colorsNight: ['#ff7fa8', '#ffd07a', '#9fe0ff'], glowNight: 0.9,
    },
    // ── STONE ────────────────────────────────────────────────────────────────
    {
      id: 'rock',        // scattered everywhere: the seabed needs grain at every depth
      count: 2000, minDepth: 0.4, maxDepth: 58.0, slopeMin: 0.32, place: 'seabed',
      clump: 14, clumpCount: 9,
      scale: [0.5, 2.6], sway: 0, roughness: 0.98, solid: true, nonUniform: true, sink: 0.3,
      colors: ['#7d8486', '#6b7274', '#8b8a80', '#5f6a70'],
      colorNight: '#2a3140', colorsNight: ['#2a3140', '#232a36'], glowNight: 0.0,
    },
    {
      id: 'boulder',     // rare big stones — landmarks you navigate a canyon by
      count: 260, minDepth: 5.0, maxDepth: 58.0, slopeMin: 0.28, place: 'seabed',
      clump: 22, clumpCount: 4,
      scale: [2.6, 7.5], sway: 0, roughness: 0.98, solid: true, nonUniform: true, sink: 0.34,
      colors: ['#71797c', '#636b6d', '#7e7f76'],
      colorNight: '#232935', colorsNight: ['#232935'], glowNight: 0.0,
    },
    // ── DEEP ─────────────────────────────────────────────────────────────────
    {
      id: 'tubeworm',    // clustered on the trench floor near the vents; the only deep flora
      count: 520, minDepth: 30.0, maxDepth: 56.0, slopeMin: 0.5, place: 'seabed',
      clump: 5, clumpCount: 16,
      height: [0.5, 1.8], sway: 0.25, swayScale: 0.4,
      color: '#b8443f', colorNight: '#5e1f2c', glowNight: 1.0,
    },
    {
      id: 'shells',      // island shallows only; keeps the one beach from reading bare
      count: 340, minDepth: 0.05, maxDepth: 3.0, slopeMin: 0.55, place: 'seabed',
      scale: [0.05, 0.14],
      colors: ['#f0e0c4', '#e8d2ae', '#f6eede'],
      colorNight: '#8a8792',
      colorsNight: ['#8a8792', '#79868c', '#76707c'], glowNight: 0.0,
    },
  ],
};

// Real-GLB catalogue bands (same contract as lagoon's catalogue-flora.js).
// Two palms on the one island, a handful of rocks — that is the whole prop
// budget above water.
export const catalogueBands = {
  palm: { count: 14, minDepth: -4.5, maxDepth: -0.6, slopeMin: 0.66 },
  reefRock: { count: 70, minDepth: 1.0, maxDepth: 12.0, slopeMin: 0.45 },
  shoreBush: { count: 12, minDepth: -1.4, maxDepth: 0.6, slopeMin: 0.58 },
};

// ─────────────────────────────────────────────────────────────────────────────
//  SPAWN POINTS & PORTALS — coordinates checked against the loaded grid via
//  bandAt/terrainHeight, not eyeballed.
// ─────────────────────────────────────────────────────────────────────────────
const SHORE_XZ = [-214, -86];  // Gullhook's south beach, looking out over the Pale Tables
const BOAT_XZ  = [-150, -40];  // afloat off the island, bow toward the trench
const DIVE_XZ  = [ -70,  40];  // the Sunder gate — trench axis, the deep descent

export const spawnPoints = {
  shore: {
    position: [SHORE_XZ[0], terrainHeight(SHORE_XZ[0], SHORE_XZ[1]) + 1.7, SHORE_XZ[1]],
    lookAt: [-170, WATER_Y - 2, 0],
    eyeHeight: 1.7,
  },
  boat: {
    position: [BOAT_XZ[0], WATER_Y + 1.2, BOAT_XZ[1]],
    lookAt: [-70, WATER_Y - 4, 40],
    eyeHeight: 1.2,
  },
  dive: {
    position: [DIVE_XZ[0], WATER_Y - 6, DIVE_XZ[1]],
    lookAt: [12, WATER_Y - 40, 54],
    eyeHeight: 1.2,
  },
};

export const portals = [
  // Back to Town. Sits in wading water on Gullhook's beach so it is reachable
  // on foot from the ship anchorage (bandAt = WADE there, ~0.8 deep).
  {
    id: 'gullhook-gate',
    x: -233, z: -103,
    targetZone: 'lagoon',
    targetPortal: 'sea-gate',
  },
  {
    id: 'sea-fjord-gate',
    x: 233, z: 103,
    targetZone: 'grassland',
    targetPortal: 'fjord-arch',
  },
];
